version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sin-ln"
s3_prefix = "sin-ln"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-aeiubs44a0lz"
