AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sin(ln)

  The headless server code for runnning the sin(ln) app.

Globals:
  Function:
    Timeout: 3
    Handler: bootstrap
    Runtime: provided.al2
    Architectures:
      - x86_64

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: sin(ln) API
      Name: sinln
      Domain:
        DomainName: api.sinln.mdsimmo.com
        CertificateArn: arn:aws:acm:ap-southeast-2:400928329577:certificate/af000f61-c599-4b7e-ac68-8fc46f8eebb5
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:3000"
          - "https://sinln.mdsimmo.com"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  MembersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: sinln-members
      PrimaryKey:
        Name: id
        Type: String

  UpdateMember:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sinln-update-member
      CodeUri: update-member/
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /update-member
            Method: Post
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref MembersTable
  
  ListMembers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sinln-list-members
      CodeUri: list-members/
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /list-members
            Method: Post
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref MembersTable

  DeleteMember:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sinln-delete-member
      CodeUri: delete-member/
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /delete-member
            Method: Post
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref MembersTable