[package]
name = "app-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = "1"
serde_json = "1"
lambda_http = "0.7"
model = "0.1.2"
aws-sdk-dynamodb = ">=0"